name: GA Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
env:
  DAY_OF_WEEK: Monday
on:
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "My name  ${{ vars.MY_NAME }} "
      - run: echo "My secrets name  ${{ secrets.MY_SECRET_NAME }}  by GitHub!"
      - run: echo "My env = by GitHub!  $DAY_OF_WEEK  "
     
